### ISSUE TITLE
simplified czech layout second row misaligned

### ISSUE THREAD

**Issue by cptMikky** [AnySoftKeyboard/LanguagePack#266]
The simplified czech qwerty layout has misaligned second row (the "ASDF" row).

The row should be aligned to the center but it is instead aligned to the left with a hole on the right (where the "Ů" symbol is on the full keyboard layout).

(Lineage 15.1 and Lineage 16, latest packages from f-droid)

**Comment by cptMikky** [comment]
Although I don't really understand why this is happening as https://github.com/AnySoftKeyboard/LanguagePack/blob/Czech/src/main/res/xml/cs_qwerty_simple.xml (line 20) looks fine.

Maybe a bug somewhere?

**Comment by ArenaL5** [comment]
F-Droid's most current download is from July 2018. Your bug was already fixed.

Line 20 in the code for the APK in F-Droid reads this:
```
    <Key android:codes="a" android:popupCharacters="\@áäα" ask:hintLabel="\@" android:keyEdgeFlags="left" />
```

Without an `android:horizontalGap="5%p"`, the second row is aligned to the left (or, presumably, to the right if you were using an RTL layout).

I don't speak Czech, but I've just published code for a similar issue in another keyboard. I'll bundle a quick fix for #267 so that hopefully, ASK's team will push both fixes to F-Droid.

**Comment by menny** [comment]
Just to be clear, updating FDroid packages **does not** require any action on my part. Anyone can do that.

The file https://gitlab.com/fdroid/fdroiddata/blob/master/metadata%2Forg.herrlado.ask.languagepack.czech.yml needs to be updated and point to the latest commit.

Unfortunately, I have no idea how to do it with the current repo layout.
If someone figures that out, it would be great.

**Comment by ArenaL5** [comment]
One still needs write access to the repo to edit that file in GitLab.

[The F-Droid metadata format specifications](https://f-droid.org/en/docs/Build_Metadata_Reference/) should help, but this... is going to be difficult.

Is there any way to build APKs for a single language, rather than for every one of them? I get the impression that it would help F-Droid to find every version of APKs. (Or at the very least, would be much faster for them.)

Or maybe you can try adding a code like this. I have no way to test it:

```
  - versionName: 2.0.3
    versionCode: 261
    commit: ec2aa6498329880127a157d2442453cce75ea854
    gradle:
      - yes
    forceversion: true
    forcevercode: true
    prebuild: sed -i -e 's/versionCode versionData.versionCode/versionCode 261/' build.gradle
    preassemble:
      - :makeDictionary
    output: add_ons_apks/release/add-on--languages-czech-apk-1.apk
```

**Comment by menny** [comment]
@ArenaL5 if we just want to build czech, then we can call `./gradlew :languages:czech:apk:assembleRelease`
This will output an APK at `add_ons_apks/release/add-on--languages-czech-apk-1.apk`
The problem is that it will be versioned with `1`

**Comment by menny** [comment]
I think I can add another command-line argument that will force the version.
Let me work on that.

@ArenaL5 thanks for finding the documentation.

**Comment by menny** [comment]
Okay, I've bumped the auto-version plugin to allow forcing build-counter value.

I think we should use this:
```
  - versionName: 4.0.634
    versionCode: 2234
    commit: 1e7ab8bc4a39d71ac67dbae9555850b087b7a289
    gradle:
      - yes
    gradleprops: forceVersionBuildCount=1234
    output: add_ons_apks/release/add-on--languages-czech-apk-2234.apk
```

**Comment by menny** [comment]
I took the values from the last deploy to Play Store in circle-ci: https://app.circleci.com/jobs/github/AnySoftKeyboard/LanguagePack/1234

**Comment by menny** [comment]
I couldn't locate how to only build the Czech APK, but since we specify the `output`, I don't think there should be a problem with building everything.

If this looks sane, I can try to push this to fdroid.

**Comment by ArenaL5** [comment]
Glad I could help. The lines I can understand look sane to me.

F-Droid documentation says that `output` is supposed to point to an unsigned APK. I think that your gradle script defaults to unsigned if it can't find any keys, so it should work when they build ASK.

If not, maybe swapping `release` for `debug` in the output path would work, but I doubt it.

**Comment by menny** [comment]
we can try out this and see if it works.

**Comment by menny** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/5752

**Comment by ArenaL5** [comment]
Line 54 needs an extra space of indentation.

...yes, I believe that's the only error. :rofl:

**Comment by menny** [comment]
```
  - versionName: 4.0.634
    versionCode: 2234
    commit: 1e7ab8bc4a39d71ac67dbae9555850b087b7a289
    gradle:
      - yes
    output: add_ons_apks/release/add-on--languages-czech-apk-2234.apk
    gradleprops:
      - forceVersionBuildCount=1234

```
